version: '2'
services:
  web:
    links:
     - "redis-master"
     - "redis-slave"
    build: 
        context: "."
        dockerfile: Dockerfile
    ports:
     - "80:80"
  redis-master:
    image: "gcr.io/google_containers/redis:e2e"
  redis-slave:
    image: "gcr.io/google_samples/gb-redisslave:v1"
